package in.sarada.collector.priceanalyzer.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "item_per_market_info")
public class ItemInfo {

    private String id;
    private String state;
    private String district;
    private String market;
    private String commodity;
    private String variety;
    private String arrival_date;
    private Double min_price;
    private Double max_price;
    private Double modal_price;


    public ItemInfo() {
        // Default constructor is required by AWS DynamoDB SDK
    }

    public ItemInfo(String id, String state, String district, String market,
                    String commodity, String variety, String arrival_date, Double min_price, Double max_price, Double modal_price) {
        this.id = id;
        this.state = state;
        this.district = district;
        this.market = market;
        this.commodity = commodity;
        this.variety = variety;
        this.arrival_date = arrival_date;
        this.min_price = min_price;
        this.max_price = max_price;
        this.modal_price = modal_price;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "state")
    public String getState() {
        return state;
    }

    @DynamoDBAttribute(attributeName = "district")
    public String getDistrict() {
        return district;
    }

    @DynamoDBAttribute(attributeName = "market")
    public String getMarket() {
        return market;
    }

    @DynamoDBAttribute(attributeName = "commodity")
    public String getCommodity() {
        return commodity;
    }

    @DynamoDBAttribute(attributeName = "variety")
    public String getVariety() {
        return variety;
    }

    @DynamoDBAttribute(attributeName = "arrival_date")
    public String getArrival_date() {
        return arrival_date;
    }

    @DynamoDBAttribute(attributeName = "min_price")
    public Double getMin_price() {
        return min_price;
    }

    @DynamoDBAttribute(attributeName = "max_price")
    public Double getMax_price() {
        return max_price;
    }

    @DynamoDBAttribute(attributeName = "modal_price")
    public Double getModal_price() {
        return modal_price;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setState(String state) {
        this.state = state;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public void setMarket(String market) {
        this.market = market;
    }

    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    public void setVariety(String variety) {
        this.variety = variety;
    }

    public void setArrival_date(String arrival_date) {
        this.arrival_date = arrival_date;
    }

    public void setMin_price(Double min_price) {
        this.min_price = min_price;
    }

    public void setMax_price(Double max_price) {
        this.max_price = max_price;
    }

    public void setModal_price(Double modal_price) {
        this.modal_price = modal_price;
    }
}
